-- 01_schema.sql
-- Oracle Database BCNF Schema for Cricket Match Information System

-- 1. TEAM Table
CREATE TABLE TEAM (
    Team_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Team_Name VARCHAR2(100) NOT NULL UNIQUE,
    Coach_Name VARCHAR2(100)
);

-- 2. PLAYER Table
-- Constraints: A player belongs to exactly one team at a time via Team_ID.
CREATE TABLE PLAYER (
    Player_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Player_Name VARCHAR2(100) NOT NULL,
    DOB DATE,
    Batting_Style VARCHAR2(50),
    Bowling_Style VARCHAR2(50),
    Team_ID NUMBER NOT NULL,
    CONSTRAINT fk_player_team FOREIGN KEY (Team_ID) REFERENCES TEAM(Team_ID) ON DELETE CASCADE
);

-- 3. MATCH Table
CREATE TABLE MATCH (
    Match_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Match_Date DATE NOT NULL,
    Venue VARCHAR2(150) NOT NULL,
    Team1_ID NUMBER NOT NULL,
    Team2_ID NUMBER NOT NULL,
    Winner_Team_ID NUMBER,
    CONSTRAINT chk_teams_different CHECK (Team1_ID <> Team2_ID),
    CONSTRAINT fk_match_team1 FOREIGN KEY (Team1_ID) REFERENCES TEAM(Team_ID),
    CONSTRAINT fk_match_team2 FOREIGN KEY (Team2_ID) REFERENCES TEAM(Team_ID),
    CONSTRAINT fk_match_winner FOREIGN KEY (Winner_Team_ID) REFERENCES TEAM(Team_ID)
);

-- 4. INNINGS Table
CREATE TABLE INNINGS (
    Innings_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Match_ID NUMBER NOT NULL,
    Innings_Number NUMBER(1) NOT NULL,
    Batting_Team_ID NUMBER NOT NULL,
    Bowling_Team_ID NUMBER NOT NULL,
    Total_Runs NUMBER DEFAULT 0,
    Total_Wickets NUMBER DEFAULT 0,
    Extras NUMBER DEFAULT 0,
    CONSTRAINT chk_innings_number CHECK (Innings_Number IN (1, 2, 3, 4)),
    CONSTRAINT chk_bat_bowl_different CHECK (Batting_Team_ID <> Bowling_Team_ID),
    CONSTRAINT fk_innings_match FOREIGN KEY (Match_ID) REFERENCES MATCH(Match_ID) ON DELETE CASCADE,
    CONSTRAINT fk_innings_batting_team FOREIGN KEY (Batting_Team_ID) REFERENCES TEAM(Team_ID),
    CONSTRAINT fk_innings_bowling_team FOREIGN KEY (Bowling_Team_ID) REFERENCES TEAM(Team_ID)
);

-- 5. BATTING_STATS Table (Associative)
CREATE TABLE BATTING_STATS (
    Player_ID NUMBER NOT NULL,
    Innings_ID NUMBER NOT NULL,
    Runs_Scored NUMBER DEFAULT 0,
    Balls_Faced NUMBER DEFAULT 0,
    Fours NUMBER DEFAULT 0,
    Sixes NUMBER DEFAULT 0,
    Dismissal_Type VARCHAR2(50) DEFAULT 'Did Not Bat',
    Bowler_ID NUMBER,
    CONSTRAINT pk_batting_stats PRIMARY KEY (Player_ID, Innings_ID),
    CONSTRAINT fk_bat_player FOREIGN KEY (Player_ID) REFERENCES PLAYER(Player_ID),
    CONSTRAINT fk_bat_innings FOREIGN KEY (Innings_ID) REFERENCES INNINGS(Innings_ID) ON DELETE CASCADE,
    CONSTRAINT fk_bat_bowler FOREIGN KEY (Bowler_ID) REFERENCES PLAYER(Player_ID)
);

-- 6. BOWLING_STATS Table (Associative)
CREATE TABLE BOWLING_STATS (
    Player_ID NUMBER NOT NULL,
    Innings_ID NUMBER NOT NULL,
    Overs_Bowled NUMBER(5,1) DEFAULT 0,
    Runs_Conceded NUMBER DEFAULT 0,
    Wickets_Taken NUMBER DEFAULT 0,
    Maidens NUMBER DEFAULT 0,
    CONSTRAINT pk_bowling_stats PRIMARY KEY (Player_ID, Innings_ID),
    CONSTRAINT fk_bowl_player FOREIGN KEY (Player_ID) REFERENCES PLAYER(Player_ID),
    CONSTRAINT fk_bowl_innings FOREIGN KEY (Innings_ID) REFERENCES INNINGS(Innings_ID) ON DELETE CASCADE
);
